USE WISE_STAGING
go
insert into M_MKT_POLO_PARAMETER(PARAMETER_ID,PARAMETER_TYPE,PARAMETER_VALUE,IS_ACTIVE,USR_CRT,DTM_CRT )
select 'marketplace_cust_acquisition'PARAMETER_ID,'STOREPROCEDURE' PARAMETER_TYPE,'spMKT_MAINDEALER_MKTPL_INS_ACQUISITION_ORI_VAL'PARAMETER_VALUE,1 IS_ACTIVE,'Maindealer' USR_CRT,getdate()DTM_CRT 

insert into M_MKT_POLO_PARAMETER(PARAMETER_ID,PARAMETER_TYPE,PARAMETER_VALUE,IS_ACTIVE,USR_CRT,DTM_CRT )
select 'maindealer_cust_acquisition'PARAMETER_ID,'STOREPROCEDURE' PARAMETER_TYPE,'spMKT_MAINDEALER_INS_ACQUISITION_ORI_VAL'PARAMETER_VALUE,1 IS_ACTIVE	,'Maindealer' USR_CRT,getdate()DTM_CRT 
 
insert into M_MKT_POLO_PARAMETER(PARAMETER_ID,PARAMETER_TYPE,PARAMETER_VALUE,IS_ACTIVE,USR_CRT,DTM_CRT )
select 'EXPIRED_TOKEN_TIME'PARAMETER_ID,'SET EXPIRED TOKEN (HOUR)' PARAMETER_TYPE,'24' PARAMETER_VALUE,1 IS_ACTIVE,'Maindealer' USR_CRT,getdate()DTM_CRT 

insert into M_MKT_POLO_PARAMETER(PARAMETER_ID,PARAMETER_TYPE,PARAMETER_VALUE,IS_ACTIVE,USR_CRT,DTM_CRT )
select 'URL_MKT_MAINDEALER_API_SENDDATA_MSS'PARAMETER_ID,'URL API UNTUK SEND DATA MAIN DEALER TO MSS' PARAMETER_TYPE,'http://10.0.88.41:80/womfmssWs/services/p/task/addTaskMainDealer' PARAMETER_VALUE,1 IS_ACTIVE,'Maindealer' USR_CRT,getdate()DTM_CRT 


insert into M_MKT_POLO_PARAMETER(PARAMETER_ID,PARAMETER_TYPE,PARAMETER_VALUE,IS_ACTIVE,USR_CRT,DTM_CRT )
select 'maindealer_upd_status_wise'PARAMETER_ID,'STOREPROCEDURE' PARAMETER_TYPE,'spWOM_MKT_MAINDEALER_APIUPDATEDATA_FROM_WISE'PARAMETER_VALUE,1 IS_ACTIVE    ,'Maindealer' USR_CRT,getdate()DTM_CRT

insert into M_MKT_POLO_PARAMETER(PARAMETER_ID,PARAMETER_TYPE,PARAMETER_VALUE,IS_ACTIVE,USR_CRT,DTM_CRT )
select 'maindealer_upd_status_mss'PARAMETER_ID,'STOREPROCEDURE' PARAMETER_TYPE,'spWOM_MKT_MAINDEALER_APIUPDATEDATA_FROM_MSS'PARAMETER_VALUE,1 IS_ACTIVE    ,'Maindealer' USR_CRT,getdate()DTM_CRT
 