USE WISE_STAGING
GO

UPDATE A
SET RESPONSE_DATE=ISNULL(RESPONSE_DATE,'11')
FROM M_MKT_POLO_QUESTION_LABEL A
WHERE QUESTION_CODE in ('BIRTH_DT')

UPDATE A
SET MAX_LENGTH=ISNULL(MAX_LENGTH,3)
FROM M_MKT_POLO_QUESTION_LABEL A
WHERE QUESTION_CODE in ('SURVEY_RT','SURVEY_RW','RT','RW')

UPDATE A
SET RESPONSE_NUMERIC=ISNULL(RESPONSE_NUMERIC,'09') 
FROM M_MKT_POLO_QUESTION_LABEL A
WHERE QUESTION_CODE in ('SURVEY_RT','SURVEY_RW','RT','RW','PHONE_NUMBER' )

 



