use WISE_STAGING

 INSERT INTO M_MKT_MARKETPLACE_PRODUCT_TYPE(PRODUCT_TYPE_CODE,PRODUCT_TYPE_DESC,DTM_CRT,USR_CRT,FLAG_MASTER_PRODUCT)
 VALUES('P3','Multiguna Barang Motor Konvensional',GETDATE(),'Maindealer','Main_Dealer')